name = "CompVeris"
uuid = "daba8e96-0cf7-4afc-9418-65786d5973e7"
authors = ["dojt <dotheis.work@gmail.com>"]
version = "0.1.0"

[deps]
CSDP = "0a46da34-8e4b-519e-b418-48813639ff34"
DOT_NiceMath = "3e56a413-cb61-4004-9b36-fbc90ffc4c6e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearAlgebraX = "9b3f67b0-2d00-526e-9884-9e4938f8fb88"
Mods = "7475f97c-0381-53b1-977b-4c60186c8d62"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25.113"
HiGHS = "1.12.1"
JSON = "0.21.4"
Printf = "1.11.0"
StatsBase = "0.34.4"
